'use strict';
// Loads app/app.js in a sandboxed vm context so its pure/round-trip logic
// (serialize, line parsing, emphasis markup, id migration, etc.) can be
// exercised from plain `node --test`, with zero new dependencies and zero
// changes to app.js itself. See CLEANUP-PLAN.md Phase 2 for why this exists
// and what it deliberately does NOT attempt (DOM layout code like
// paginateBlocks needs a real browser and is out of scope here).
//
// How it works: app.js assumes a browser (document/window/fetch/etc. at
// module scope, including a few unguarded top-level calls at the very
// bottom — initControls(), fetch('/api/auth/me'), navigateTo('board'), ...).
// We stub just enough of the browser surface that those calls no-op instead
// of throwing, then append a footer (in the SAME script, so it shares the
// same lexical scope) that copies the functions/state we want to test onto
// a global we can read back after vm.runInContext returns. Function
// declarations and the top-level `const`/`let` bindings they close over stay
// reachable via closure even though they're never global-object properties.
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const APP_JS_PATH = path.join(__dirname, '..', 'app', 'app.js');
// data.js is evaluated ahead of app.js in the same script, so SHOWS, NOVELS,
// TEMPLATES, FN and the rest are the REAL ones. This used to be a two-key
// `SHOWS` stub on the sandbox, which meant every global data.js declares was
// one boot-path reference away from a ReferenceError — and that is exactly
// what happened: openReference() gained a NOVELS lookup, the boot tail's
// fallback hit it asynchronously (past the try/catch), and all four test files
// went red on teardown while every assertion in them passed. Loading the file
// costs a few ms and removes the whole category.
const DATA_JS_PATH = path.join(__dirname, '..', 'app', 'data.js');
// atlas-data.js is generated by corpus/build-atlas-data.mjs and declares
// ATLAS_DATA / ATLAS_SHOWS as plain top-level consts, exactly like data.js.
// Loaded here so corpus-driven UI (the Atlas, the Score Field) can be smoke
// tested against the REAL 1,809-song array instead of guarding out on a
// missing global and silently testing nothing.
const ATLAS_JS_PATH = path.join(__dirname, '..', 'app', 'atlas-data.js');

// Any DOM-ish call chain (document.getElementById(...).classList.toggle(...),
// element.style.display = 'none', etc.) resolves through this without
// throwing: every property access and every call returns another one of
// these. We don't care that the *results* are meaningless — only that
// app.js's boot-time DOM calls don't crash before we can extract functions.
function makeDomStub(label) {
  const target = function domStub() {};
  const handler = {
    get(t, prop) {
      if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
      // A stub node has no children, so spreading one yields nothing —
      // `[...el.children]`, `[...querySelectorAll(…)]` and `for…of` all work
      // and simply iterate zero times, matching the `length: 0` below. This
      // used to return undefined, which made any spread throw
      // "children is not iterable" — a failure about the harness that reads
      // like a failure in the page under test (it is how the Library Atlas
      // first came up red).
      if (prop === Symbol.iterator) return function* () {};
      if (prop === 'length') return 0;
      if (!(prop in t)) t[prop] = makeDomStub(label + '.' + String(prop));
      return t[prop];
    },
    set(t, prop, value) { t[prop] = value; return true; },
    apply() { return makeDomStub(label + '()'); },
    has() { return true; },
  };
  return new Proxy(target, handler);
}

function makeSandbox() {
  const storage = new Map();
  const localStorage = {
    getItem: (k) => (storage.has(k) ? storage.get(k) : null),
    setItem: (k, v) => { storage.set(k, String(v)); },
    removeItem: (k) => { storage.delete(k); },
  };
  const fakeFetch = () => Promise.resolve({
    ok: false, status: 0,
    json: () => Promise.resolve(null),
    text: () => Promise.resolve(''),
  });
  const sandbox = {
    console,
    document: makeDomStub('document'),
    navigator: {},
    location: { hostname: 'localhost', href: 'http://localhost/', protocol: 'http:' },
    localStorage,
    fetch: fakeFetch,
    setTimeout, clearTimeout, setInterval, clearInterval,
    requestAnimationFrame: () => 0,
    btoa: (s) => Buffer.from(s, 'binary').toString('base64'),
    atob: (s) => Buffer.from(s, 'base64').toString('binary'),
    escape, unescape,
    // data.js is loaded for real (see DATA_JS_PATH). lyric.js is not: it fetches
    // a 2MB pronunciation dictionary at runtime, so it stays a stub, and nothing
    // under test needs a real syllable count.
    LYRIC: { load: () => {}, ready: () => true, inDict: () => true, lineSyll: () => 0, setStrip: () => {} },
  };
  sandbox.window = sandbox;
  sandbox.globalThis = sandbox;
  return sandbox;
}

// Functions/state pulled out for testing. Add to this list if a future test
// needs another pure function — nothing else about the harness has to change.
const EXPORTS = [
  'state', 'uid', 'countWords', 'seamlessToLines', 'linesToSeamless',
  'mergeLineIds', 'stampRevisions', 'emphToHtml', 'emphFromNode', 'escHtml',
  'migrateDna', 'migrateLegacyIds', 'cardFromStored', 'serialize', 'applyShowData',
  'cardBodyField', 'b64encode', 'b64decode',
  // From data.js, so a test can assert the harness really loaded it rather than
  // running against stubs (see harness.test.js).
  'SHOWS', 'NOVELS', 'TEMPLATES',
  // From atlas-data.js, plus the corpus-driven page builders they feed.
  'ATLAS_DATA', 'ATLAS_SHOWS', 'buildScoreFieldPage', 'buildRidgelinePage',
  'buildAtlasPage', 'buildDnaAtlas', 'navigateTo',
  // FN maps every card function key to its family colour + label; the
  // Ridgeline test asserts the corpus never outgrows it.
  'FN',
  // The Board's bin: the card moves in and out of it, and render() for the
  // drawer runs against the DOM stub.
  'binCard', 'unbinCard', 'putBackCard', 'renderBin',
];

// app.js's boot tail kicks off loadProjects().then(...) — an async chain that
// finishes long after vm.runInContext has returned, and therefore outside the
// synchronous try/catch around `boot` below. There is deliberately NO allowlist
// here: an unhandled rejection out of the boot path means the sandbox is missing
// something app.js now needs, which is a fact about the harness worth failing
// on. The previous version swallowed anything matching /SHOWS|LYRIC/, which is
// how a real gap (openReference's NOVELS lookup) sat unnoticed behind four red
// test files whose assertions were all passing.
let _rejectionGuardInstalled = false;
function installRejectionGuard() {
  if (_rejectionGuardInstalled) return;
  _rejectionGuardInstalled = true;
  process.on('unhandledRejection', (err) => {
    throw new Error('load-app.js: app.js boot rejected — the sandbox is missing '
      + 'something app.js needs. Add it to makeSandbox(). Cause: ' + (err && err.stack || err));
  });
}

function loadApp() {
  installRejectionGuard();
  const src = fs.readFileSync(APP_JS_PATH, 'utf8');
  const data = fs.readFileSync(DATA_JS_PATH, 'utf8');
  const atlas = fs.readFileSync(ATLAS_JS_PATH, 'utf8');

  // Split right before the unguarded boot section (initControls(); and the
  // fetch/navigateTo/loadProjects calls after it) so a throw in there can't
  // prevent our export footer — appended after everything — from running.
  const bootMarker = '\ninitControls();';
  const splitAt = src.indexOf(bootMarker);
  if (splitAt < 0) throw new Error('load-app.js: boot marker not found — did app.js change shape?');
  const declarations = src.slice(0, splitAt);
  const boot = src.slice(splitAt);

  const footer = '\n;globalThis.__TEST_EXPORTS__ = {\n' +
    EXPORTS.map((n) => '  ' + n + ": (typeof " + n + " !== 'undefined' ? " + n + ' : undefined),').join('\n') +
    '\n};\n';

  // data.js first, in the same script so its top-level `const`s (SHOWS, NOVELS,
  // TEMPLATES, FN, DEFAULT_TEMPLATE…) are in scope for app.js exactly as they
  // are in the browser, where index.html loads them as two plain script tags.
  const wrapped = data + '\n' + atlas + '\n' + declarations
    + '\ntry {' + boot + '\n} catch (_) { /* boot-time DOM calls; irrelevant to extracted functions */ }'
    + footer;

  const context = vm.createContext(makeSandbox());
  vm.runInContext(wrapped, context, { filename: 'app.js (sandboxed for tests)' });

  const exported = context.__TEST_EXPORTS__;
  if (!exported || typeof exported.serialize !== 'function') {
    throw new Error('load-app.js: extraction failed — __TEST_EXPORTS__ missing expected functions');
  }
  return exported;
}

module.exports = { loadApp };
