// Seed reference shows for the board shell. Each number is a compact tuple:
// [act, title, fn, voicing, estMinutes]
// Keys / BPM / exact runtimes intentionally omitted ("needs score").

// Default template applied to every new user project.
// 15 blank song cards placed in statistically typical act positions.
// Lane mapping: '1' = Act 1 (pre-break), '2A' = build to intermission,
// '2B' = post-intermission, '3' = late Act 2 through close.
// INTERMISSION marker renders between 2A and 2B.
const DEFAULT_TEMPLATE = [
  // ── Act 1: establish world, voice, first hook ───────────────────
  { act: '1',  type: 'song', title: '', fn: 'opening', voicing: '', min: 4   },
  { act: '1',  type: 'song', title: '', fn: 'charm',   voicing: '', min: 3   },
  { act: '1',  type: 'song', title: '', fn: 'iwant',   voicing: '', min: 3.5 },
  // ── Act 2A: complications deepen → threat crystallizes → cliffhanger
  { act: '2A', type: 'song', title: '', fn: 'comedy',  voicing: '', min: 2.5 },
  { act: '2A', type: 'song', title: '', fn: 'love',    voicing: '', min: 3.5 },
  { act: '2A', type: 'song', title: '', fn: 'villain', voicing: '', min: 2.5 },
  { act: '2A', type: 'song', title: '', fn: 'anthem',  voicing: '', min: 3.5 },
  { act: '2A', type: 'song', title: '', fn: 'finale',  voicing: '', min: 4   },
  // ── Act 2B: regroup → cost mounts → late-act drive ──────────────
  { act: '2B', type: 'song', title: '', fn: 'charm',      voicing: '', min: 3   },
  { act: '2B', type: 'song', title: '', fn: 'ballad',     voicing: '', min: 3.5 },
  { act: '2B', type: 'song', title: '', fn: 'reprise',    voicing: '', min: 2   },
  { act: '2B', type: 'song', title: '', fn: 'production', voicing: '', min: 4.5 },
  { act: '2B', type: 'song', title: '', fn: 'anthem',     voicing: '', min: 3.5 },
  // ── Act 3: climax → resolution ──────────────────────────────────
  { act: '3',  type: 'song', title: '', fn: 'eleven',       voicing: '', min: 4.5 },
  { act: '3',  type: 'song', title: '', fn: 'finaleultimo', voicing: '', min: 3   },
];

const FN = {
  opening:      { fam: 'blue',   label: 'Opening' },
  iwant:        { fam: 'teal',   label: 'I Want' },
  charm:        { fam: 'amber',  label: 'Charm' },
  love:         { fam: 'pink',   label: 'Love' },
  production:   { fam: 'coral',  label: 'Production' },
  soliloquy:    { fam: 'purple', label: 'Soliloquy' },
  ballad:       { fam: 'purple', label: 'Ballad' },
  finale:       { fam: 'blue',   label: 'Act Finale' },
  eleven:       { fam: 'red',    label: "11 O'Clock" },
  reprise:      { fam: 'gray',   label: 'Reprise' },
  finaleultimo: { fam: 'green',  label: 'Finale' },
  villain:      { fam: 'red',    label: 'Villain' },
  comedy:       { fam: 'amber',  label: 'Comedy' },
  anthem:       { fam: 'coral',  label: 'Anthem' },
  diegetic:     { fam: 'gray',   label: 'Diegetic' },
  establishing: { fam: 'gray',   label: 'Establishing' },
  drive:        { fam: 'gray',   label: 'Plot' },
  motif:        { fam: 'green',  label: 'Motif' },
};


const SHOWS = {
  fiddler: {
    title: 'Fiddler on the Roof', year: 1964, form: 'two-act',
    teaches: 'Opening number ("Tradition") establishes world + rules',
    numbers: [
      [1, 'Tradition (Prologue)', 'opening', 'Tevye + Company', 6.5, 7, 3],
      [1, 'Matchmaker, Matchmaker', 'charm', 'Daughters', 3.5, 5, 3],
      [1, 'If I Were a Rich Man', 'iwant', 'Tevye', 4.5, 6, 4],
      [1, 'Sabbath Prayer', 'ballad', 'Tevye, Golde, Co.', 2.5, 3, 4],
      [1, 'To Life (L\'Chaim)', 'production', 'Tevye, Lazar, Men', 4, 9, 5],
      [1, 'Miracle of Miracles', 'charm', 'Motel', 2.5, 6, 4],
      [1, 'The Dream', 'production', 'Tevye, Golde, Ens.', 5, 8, 6],
      [1, 'Sunrise, Sunset', 'finale', 'Company', 4, 5, 7],
      [2, 'Now I Have Everything', 'love', 'Perchik, Hodel', 2.5, 5, 6],
      [2, 'Do You Love Me?', 'love', 'Tevye, Golde', 3, 4, 5],
      [2, 'The Rumor', 'comedy', 'Yente, Villagers', 1.5, 6, 5],
      [2, 'Far From the Home I Love', 'ballad', 'Hodel', 3, 4, 7],
      [2, 'Chavaleh (Little Bird)', 'soliloquy', 'Tevye', 2, 3, 8],
      [2, 'Anatevka', 'finaleultimo', 'Company', 3, 4, 9],
    ],
  },
  gypsy: {
    title: 'Gypsy', year: 1959, form: 'two-act',
    teaches: 'The definitive 11 o\'clock number + driving Act 1 finale',
    numbers: [
      [1, 'Let Me Entertain You (kiddie)', 'diegetic', 'Baby June & Louise', 2, 5, 2],
      [1, 'Some People', 'iwant', 'Rose', 3.5, 6, 4],
      [1, 'Small World', 'love', 'Rose, Herbie', 2.5, 4, 3],
      [1, 'Baby June and Her Newsboys', 'diegetic', 'Baby June + kids', 2, 6, 2],
      [1, 'Mr. Goldstone, I Love You', 'comedy', 'Rose, Company', 2.5, 7, 3],
      [1, 'Little Lamb', 'soliloquy', 'Louise', 2, 2, 4],
      [1, 'You\'ll Never Get Away from Me', 'love', 'Rose, Herbie', 2.5, 4, 3],
      [1, 'Dainty June and Her Farmboys', 'diegetic', 'June + Company', 3, 6, 3],
      [1, 'If Momma Was Married', 'charm', 'June, Louise', 3, 4, 4],
      [1, 'All I Need Is the Girl', 'charm', 'Tulsa', 4, 5, 4],
      [1, 'Everything\'s Coming Up Roses', 'finale', 'Rose', 3.5, 8, 7],
      [2, 'Madame Rose\'s Toreadorables', 'diegetic', 'Rose, Louise, Co.', 2, 6, 4],
      [2, 'Together Wherever We Go', 'charm', 'Rose, Herbie, Louise', 3, 6, 4],
      [2, 'You Gotta Get a Gimmick', 'comedy', 'Tessie, Mazeppa, Electra', 4, 6, 3],
      [2, 'Let Me Entertain You (strip)', 'diegetic', 'Louise / Gypsy', 3.5, 5, 6],
      [2, 'Rose\'s Turn', 'eleven', 'Rose', 4.5, 7, 10],
    ],
  },
  newsies: {
    title: 'Newsies', year: 2012, form: 'two-act',
    teaches: 'Anthem + ensemble production numbers; high-energy contemporary',
    numbers: [
      [1, 'Santa Fe (Prologue)', 'iwant', 'Jack, Crutchie', 2, 4, 3],
      [1, 'Carrying the Banner', 'opening', 'Jack, Davey, Newsies', 4.5, 8, 3],
      [1, 'The Bottom Line', 'villain', 'Pulitzer + cronies', 2.5, 5, 5],
      [1, 'That\'s Rich', 'diegetic', 'Medda Larkin', 2.5, 6, 2],
      [1, 'I Never Planned on You', 'charm', 'Jack, Bowery Beauties', 3, 5, 3],
      [1, 'The World Will Know', 'anthem', 'Jack, Davey, Les, Newsies', 3.5, 8, 6],
      [1, 'Watch What Happens', 'iwant', 'Katherine', 2.5, 5, 4],
      [1, 'Seize the Day', 'production', 'Davey, Jack, Les, Newsies', 4.5, 9, 6],
      [1, 'Santa Fe', 'finale', 'Jack', 4, 7, 7],
      [2, 'King of New York', 'production', 'Davey, Katherine, Les, Newsies', 4.5, 9, 4],
      [2, 'Letter from the Refuge', 'ballad', 'Crutchie', 2.5, 3, 6],
      [2, 'Watch What Happens (Reprise)', 'reprise', 'Jack, Davey, Les, Katherine', 1.5, 5, 6],
      [2, 'Brooklyn\'s Here', 'production', 'Spot Conlon, Newsies', 2.5, 8, 6],
      [2, 'Something to Believe In', 'love', 'Jack, Katherine', 3.5, 4, 5],
      [2, 'Once and for All', 'anthem', 'Jack, Katherine, Davey, Newsies', 3.5, 8, 8],
      [2, 'Finale (Santa Fe reprise)', 'finaleultimo', 'Company', 2, 7, 3],
    ],
    // Full scene-by-scene story: 16 songs + ~38 book-scene beats, hand-placed lanes.
    // Break into 2 = "The World Will Know"; intermission after "Santa Fe";
    // Break into 3 (Act 3 start) = "Brooklyn's Here".
    cards: [
      // ACT 1
      { lane: '1', type: 'scene', title: 'Brooklyn Rooftop' },
      { lane: '1', type: 'song', title: 'Santa Fe (Prologue)', fn: 'iwant', voicing: 'Jack, Crutchie', min: 2 },
      { lane: '1', type: 'beat', title: 'Rooftop at dawn', note: 'Jack sketches the Santa Fe dream; Crutchie\'s bad leg, his loyalty', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Snyder the Spider', note: 'The Refuge warden hunts runaways; Jack, an escapee, keeps his head down', min: 1 },
      { lane: '1', type: 'scene', title: 'Streets of Manhattan' },
      { lane: '1', type: 'song', title: 'Carrying the Banner', fn: 'opening', voicing: 'Jack, Newsies', min: 4.5 },
      { lane: '1', type: 'beat', title: 'The distribution gates', note: 'Wiesel and the Delanceys hawk the papes; Davey and Les arrive needing to earn', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Jack takes the boys in', note: 'He teaches Davey & Les to sell — and sizes up his new partners', min: 1.5 },
      { lane: '1', type: 'scene', title: "Pulitzer's Office" },
      { lane: '1', type: 'song', title: 'The Bottom Line', fn: 'villain', voicing: 'Pulitzer + cronies', min: 2.5 },
      { lane: '1', type: 'beat', title: 'The price hike hits', note: 'The World ups the price 10¢ per hundred; Davey names it — they\'re being robbed', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Scuffle at the gates', note: 'The Delanceys shove Les; Jack steps in; the boys duck into Medda\'s', min: 1.5 },
      { lane: '1', type: 'scene', title: "Medda's Theater" },
      { lane: '1', type: 'song', title: "That's Rich", fn: 'diegetic', voicing: 'Medda Larkin', min: 2.5 },
      { lane: '1', type: 'beat', title: 'Jack meets Katherine', note: 'Sparks in the wings with the young reporter; he sketches her', min: 1.5 },
      { lane: '1', type: 'song', title: 'I Never Planned on You', fn: 'charm', voicing: 'Jack', min: 3 },
      { lane: '1', type: 'beat', title: 'The idea: a strike', note: 'Jack pitches it; Davey the reluctant brains signs on', min: 1.5 },
      // ACT 2A
      { lane: '2A', type: 'scene', title: 'Newsies Square' },
      { lane: '2A', type: 'song', title: 'The World Will Know', fn: 'anthem', voicing: 'Jack, Davey, Les, Newsies', min: 3.5 },
      { lane: '2A', type: 'beat', title: 'Forming the union', note: 'The newsies organize and name Jack & Davey their leaders', min: 1.5 },
      { lane: '2A', type: 'scene', title: 'The Sun — City Room' },
      { lane: '2A', type: 'beat', title: 'Katherine smells a story', note: 'She pitches the strike to her skeptical editor', min: 1.5 },
      { lane: '2A', type: 'song', title: 'Watch What Happens', fn: 'iwant', voicing: 'Katherine', min: 2.5 },
      { lane: '2A', type: 'scene', title: 'Distribution Gates — Strike Day' },
      { lane: '2A', type: 'beat', title: 'Strike morning', note: 'The newsies mass at the distribution window and refuse to sell', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'The scabs arrive', note: 'Wiesel brings in replacement boys to sell the papes', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'Winning over the scabs', note: 'The newsies argue, shame, and welcome the scabs into the cause', min: 2 },
      { lane: '2A', type: 'song', title: 'Seize the Day', fn: 'production', voicing: 'Davey, Jack, Les, Newsies', min: 4.5 },
      { lane: '2A', type: 'beat', title: 'The crackdown', note: 'The Delanceys and police charge; the rally erupts into a riot', min: 2 },
      { lane: '2A', type: 'beat', title: 'Crutchie is taken', note: 'Snyder\'s men beat Crutchie and drag him to the Refuge', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'Jack runs', note: 'Alone on the rooftop, blaming himself, watching the city', min: 1 },
      { lane: '2A', type: 'song', title: 'Santa Fe', fn: 'finale', voicing: 'Jack', min: 4 },
      // ACT 2B
      { lane: '2B', type: 'scene', title: 'Newsies Lodging House' },
      { lane: '2B', type: 'beat', title: 'Front page', note: 'The strike is the talk of the city; the newsies are famous', min: 1.5 },
      { lane: '2B', type: 'song', title: 'King of New York', fn: 'production', voicing: 'Davey, Katherine, Les, Newsies', min: 4.5 },
      { lane: '2B', type: 'scene', title: "Medda's — Backstage" },
      { lane: '2B', type: 'beat', title: 'Jack in hiding', note: 'Painting backdrops at Medda\'s, done with the fight', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'Katherine pushes back', note: 'She refuses to let him quit', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'At the Refuge', note: 'Crutchie, hurting but unbroken, dreams of Jack and Santa Fe', min: 1 },
      { lane: '2B', type: 'song', title: 'Letter from the Refuge', fn: 'ballad', voicing: 'Crutchie', min: 2.5 },
      { lane: '2B', type: 'beat', title: "Katherine's secret", note: 'She\'s Pulitzer\'s daughter; trust wobbles', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'The plan', note: 'Rally every working kid in New York; beat Pulitzer with his own press', min: 1.5 },
      { lane: '2B', type: 'song', title: 'Watch What Happens (Reprise)', fn: 'reprise', voicing: 'Jack, Davey, Les, Katherine', min: 1.5 },
      { lane: '2B', type: 'scene', title: "Pulitzer's Office" },
      { lane: '2B', type: 'beat', title: 'Summoned by Pulitzer', note: 'Jack is hauled before Pulitzer; Snyder waits in the office', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'The bribe', note: 'Money and freedom from the Refuge if Jack calls off the strike', min: 2 },
      { lane: '2B', type: 'beat', title: 'Jack folds', note: 'Publicly he tells the boys to give up; the cause looks dead — all is lost', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'Betrayed', note: 'Davey and the newsies turn on Jack; Katherine won\'t quit', min: 1.5 },
      // ACT 3
      { lane: '3', type: 'scene', title: 'The Streets — Midtown' },
      { lane: '3', type: 'song', title: "Brooklyn's Here", fn: 'production', voicing: 'Spot Conlon, Newsies', min: 2.5 },
      { lane: '3', type: 'beat', title: 'Jack recommits', note: 'Katherine shows him the way; the cellar printing plan', min: 1.5 },
      { lane: '3', type: 'song', title: 'Something to Believe In', fn: 'love', voicing: 'Jack, Katherine', min: 3.5 },
      { lane: '3', type: 'scene', title: "The World's Press Room" },
      { lane: '3', type: 'beat', title: 'Printing the Banner', note: 'Overnight, in the World\'s own cellar, they print their paper', min: 2 },
      { lane: '3', type: 'beat', title: 'The city rises', note: 'Every working kid in New York reads the call to strike', min: 1.5 },
      { lane: '3', type: 'song', title: 'Once and for All', fn: 'anthem', voicing: 'Jack, Katherine, Davey, Newsies', min: 3.5 },
      { lane: '3', type: 'beat', title: 'Roosevelt arrives', note: 'Jack\'s Refuge drawings expose Snyder; the Governor intervenes', min: 2 },
      { lane: '3', type: 'beat', title: 'Pulitzer concedes', note: 'Snyder arrested, Crutchie freed, the price rolled back', min: 1.5 },
      { lane: '3', type: 'beat', title: 'Jack stays', note: 'He chooses New York, Katherine, and the newsies over Santa Fe', min: 1.5 },
      { lane: '3', type: 'song', title: 'Finale (Santa Fe reprise)', fn: 'finaleultimo', voicing: 'Company', min: 2 },
    ],
  },
  evanhansen: {
    title: 'Dear Evan Hansen', year: 2015, form: 'two-act',
    teaches: 'Contemporary intimate pop; a small lie as engine; the Act 1 finale that goes viral',
    // ENRICHED reference (2026-06-23): the flagship study object — full scene/beat
    // scaffolding, character registry, and title page authored from public synopsis
    // and the documented running order. No lyrics are reproduced anywhere (the
    // manuscript shows structure + cue lines only). Runtimes are interpretive
    // ballparks; keys/tempo are "needs score" and left unset.
    characters: {
      'EVAN HANSEN': { voiceType: 'Tenor', desc: 'Anxious, isolated high-school senior; the protagonist whose small lie spirals out of his control.' },
      'HEIDI HANSEN': { voiceType: 'Mezzo-Soprano', desc: "Evan's mother; a nurse's aide studying law on the side. Stretched thin, perpetually absent, fiercely loving single parent." },
      'ZOE MURPHY': { voiceType: 'Mezzo-Soprano', desc: "Connor's younger sister. Clear-eyed and guarded; a musician. Evan's love interest, unwilling to mourn the brother who frightened her." },
      'CONNOR MURPHY': { voiceType: 'Tenor', desc: 'A troubled, angry classmate whose death by suicide sets the story in motion. Returns as the confident, imagined version Evan invents.' },
      'CYNTHIA MURPHY': { voiceType: 'Mezzo-Soprano', desc: "Connor and Zoe's mother. Desperate to believe her son was loved and known; seizes on Evan as proof." },
      'LARRY MURPHY': { voiceType: 'Baritone', desc: "Connor and Zoe's father. Reserved, practical, grieving a son he could never reach — and drawn to Evan as a surrogate." },
      'JARED KLEINMAN': { voiceType: 'Tenor', desc: "Evan's sardonic \"family friend.\" Forges the backlog of fake emails for laughs, then watches the lie metastasize." },
      'ALANA BECK': { voiceType: 'Mezzo-Soprano', desc: 'An over-involved, lonely overachiever who founds and drives the Connor Project, hungry to matter.' },
    },
    titlePage: {
      subtitle: 'A New Musical',
      authors: 'Music & Lyrics by Benj Pasek & Justin Paul · Book by Steven Levenson',
      settings: ['The present day', 'A suburban American town', 'The Hansen home, the Murphy home, and the high school'],
      productionNotes: 'Reference study object — structural scaffold only; no lyric text is reproduced. Contains mature themes: teen suicide, mental health, social anxiety.',
    },
    cards: [
      // ===== ACT ONE (lanes 1 + 2A) =====
      { lane: '1', type: 'scene', title: 'The Hansen Kitchen / The Murphy Kitchen' },
      { lane: '1', type: 'song', title: 'Anybody Have a Map?', fn: 'opening', voicing: 'Heidi, Cynthia', min: 2.5 },
      { lane: '1', type: 'beat', title: 'Two mothers, two mornings', note: 'Heidi and Cynthia each try and fail to reach their sons before school — establishing the parallel broken households.', min: 1.5 },
      { lane: '1', type: 'beat', title: "The therapy-letter assignment", note: "Evan's therapist has him write a daily pep-talk letter to himself. The letter device that will drive the whole plot is planted here.", min: 1 },
      { lane: '1', type: 'scene', title: 'High School — First Day Back' },
      { lane: '1', type: 'beat', title: 'Invisible in the halls', note: "Arm in a cast, Evan can't get anyone to sign it. Jared needles him, Alana barely remembers him — total social erasure.", min: 1.5 },
      { lane: '1', type: 'song', title: 'Waving Through a Window', fn: 'iwant', voicing: 'Evan, Company', min: 3.5 },
      { lane: '1', type: 'scene', title: 'The Computer Lab' },
      { lane: '1', type: 'beat', title: 'Connor signs the cast', note: "After a hallway blow-up, Connor signs Evan's cast — a hostile joke that still lands as the only contact Evan gets all day.", min: 1.5 },
      { lane: '1', type: 'beat', title: 'The letter is taken', note: "Connor finds Evan's printed therapy letter (it names Zoe) and pockets it, certain Evan wrote it to mock him.", min: 1 },
      { lane: '1', type: 'scene', title: 'The Murphy Home — A Few Days Later' },
      { lane: '1', type: 'beat', title: "Connor's death", note: "The Murphys learn Connor has taken his own life. The letter is found on him and mistaken for his suicide note — addressed, it seems, to Evan.", min: 1.5 },
      { lane: '1', type: 'beat', title: 'The misunderstanding', note: 'Cynthia and Larry believe Evan was Connor’s secret best friend. Panicking, Evan fails to correct them — and the lie is born.', min: 1.5 },
      { lane: '1', type: 'song', title: 'For Forever', fn: 'charm', voicing: 'Evan', min: 3.5 },
      { lane: '1', type: 'beat', title: 'Inventing a friendship', note: 'To comfort the grieving Murphys, Evan fabricates a perfect afternoon he and Connor never shared. The lie becomes beautiful — and irresistible.', min: 1 },
      { lane: '1', type: 'scene', title: "Evan's Bedroom" },
      { lane: '1', type: 'beat', title: 'Backfilling the lie', note: 'To make the friendship believable, Evan enlists Jared to forge a backlog of emails between him and Connor.', min: 1.5 },
      { lane: '1', type: 'song', title: 'Sincerely, Me', fn: 'comedy', voicing: 'Evan, Jared, Connor', min: 3.5 },

      { lane: '2A', type: 'scene', title: 'The Murphy Living Room' },
      { lane: '2A', type: 'song', title: 'Requiem', fn: 'ballad', voicing: 'Zoe, Cynthia, Larry', min: 3.5 },
      { lane: '2A', type: 'beat', title: 'Three kinds of grief', note: 'Cynthia clings to the myth of a good son; Larry stays guarded; Zoe refuses to mourn a brother who frightened her. The family fractures along the lie.', min: 1.5 },
      { lane: '2A', type: 'scene', title: 'The Murphy House — Later' },
      { lane: '2A', type: 'beat', title: 'Evan offers Zoe "proof"', note: 'Drawn to Zoe, Evan gives her evidence that Connor secretly loved her — words he is really inventing.', min: 1.5 },
      { lane: '2A', type: 'song', title: 'If I Could Tell Her', fn: 'love', voicing: 'Evan, Zoe', min: 3.5 },
      { lane: '2A', type: 'beat', title: "Evan's feelings in Connor's mouth", note: 'Every tender observation Evan attributes to Connor is his own. The lie and the truth fuse — Evan courts Zoe through her dead brother.', min: 1 },
      { lane: '2A', type: 'scene', title: 'The School — The Connor Project Forms' },
      { lane: '2A', type: 'beat', title: 'Alana drives the cause', note: 'Alana and Jared propose a project to keep Connor’s memory alive; Evan is pushed reluctantly to the center of it.', min: 1.5 },
      { lane: '2A', type: 'song', title: 'Disappear', fn: 'anthem', voicing: 'Connor, Evan, Company', min: 3.5 },
      { lane: '2A', type: 'beat', title: '"No one deserves to disappear"', note: "The imagined Connor hands Evan the mission and the slogan that will go viral. Evan's invisibility becomes a movement.", min: 1 },
      { lane: '2A', type: 'scene', title: 'The Connor Project Assembly' },
      { lane: '2A', type: 'beat', title: 'The speech', note: 'Evan freezes at the podium, then finds the words — speaking, really, about his own loneliness and longing to be found.', min: 1.5 },
      { lane: '2A', type: 'song', title: 'You Will Be Found', fn: 'finale', voicing: 'Evan, Alana, Jared, Zoe, Company', min: 4.5 },
      { lane: '2A', type: 'beat', title: 'It goes viral', note: 'The speech explodes online; strangers share it; Evan is suddenly seen by everyone. The Act One curtain — built entirely on a lie.', min: 1 },

      // ===== ACT TWO (lanes 2B + 3) =====
      { lane: '2B', type: 'scene', title: "Evan's Bedroom — The Project Grows" },
      { lane: '2B', type: 'song', title: 'Sincerely, Me (Reprise)', fn: 'reprise', voicing: 'Jared, Connor, Evan', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'Feeding the machine', note: 'The fabricated emails keep multiplying to sustain the Connor Project as it balloons beyond Evan’s control.', min: 1 },
      { lane: '2B', type: 'scene', title: 'The Murphy Home — The Study' },
      { lane: '2B', type: 'beat', title: 'A surrogate son', note: 'Larry, who never connected with Connor, begins to connect with Evan instead.', min: 1.5 },
      { lane: '2B', type: 'song', title: 'To Break in a Glove', fn: 'charm', voicing: 'Larry, Evan', min: 3.5 },
      { lane: '2B', type: 'scene', title: 'The Orchard' },
      { lane: '2B', type: 'beat', title: 'Real, for a moment', note: "Evan and Zoe alone. For the first time the connection isn't borrowed from the lie — it's actually theirs.", min: 1.5 },
      { lane: '2B', type: 'song', title: 'Only Us', fn: 'love', voicing: 'Zoe, Evan', min: 3.5 },
      { lane: '2B', type: 'scene', title: 'The Hansen Kitchen' },
      { lane: '2B', type: 'beat', title: 'Heidi on the outside', note: 'Evan’s mother sees how much of her son now belongs to the Murphys — and finds the viral speech online, blindsided.', min: 1.5 },
      { lane: '2B', type: 'song', title: 'Good for You', fn: 'drive', voicing: 'Heidi, Alana, Jared, Evan', min: 3.5 },
      { lane: '2B', type: 'beat', title: 'The walls close in', note: 'Heidi, Alana, and Jared each turn on Evan as the contradictions surface. The lie starts to come apart.', min: 1.5 },

      { lane: '3', type: 'beat', title: 'The point of no return', note: 'The Murphys plan to make the (fake) email archive public. Evan must finally tell the truth or let the lie become permanent.', min: 1.5 },
      { lane: '3', type: 'scene', title: 'The Murphy Living Room' },
      { lane: '3', type: 'beat', title: 'Telling the truth', note: 'Evan confesses to the Murphys that he and Connor were never friends — that he invented all of it.', min: 1.5 },
      { lane: '3', type: 'song', title: 'Words Fail', fn: 'eleven', voicing: 'Evan', min: 4 },
      { lane: '3', type: 'beat', title: 'The reckoning', note: "Stripped of the story, Evan faces what he did and why he needed it. The show's 11 o'clock number — the bottom.", min: 1 },
      { lane: '3', type: 'scene', title: 'The Hansen Kitchen' },
      { lane: '3', type: 'beat', title: 'Mother and son', note: "Heidi doesn't rage. She tells Evan about the night his father left — and promises she will not.", min: 1.5 },
      { lane: '3', type: 'song', title: 'So Big / So Small', fn: 'ballad', voicing: 'Heidi', min: 3 },
      { lane: '3', type: 'scene', title: 'The Orchard — One Year Later' },
      { lane: '3', type: 'beat', title: 'Aftermath and repair', note: 'Evan has come clean; the Connor Project endures honestly. He has spent the year learning who he is without the lie.', min: 1.5 },
      { lane: '3', type: 'beat', title: 'Reconciliation', note: 'Zoe meets him again, changed. She forgives without reuniting — and Evan, at last, is seen as himself.', min: 1 },
      { lane: '3', type: 'song', title: 'Finale (You Will Be Found reprise)', fn: 'finaleultimo', voicing: 'Company', min: 3 },
    ],
  },
  hamilton: {
    title: 'Hamilton', year: 2015, form: 'two-act',
    teaches: 'Through-composition + motif density; delayed payoff',
    numbers: [
      [1, 'Alexander Hamilton', 'opening', 'Company', 4, 6, 3],
      [1, 'Aaron Burr, Sir', 'establishing', 'Burr, Hamilton +3', 2.5, 5, 3],
      [1, 'My Shot', 'iwant', 'Hamilton +3', 5.5, 8, 4],
      [1, 'The Story of Tonight', 'anthem', 'Hamilton + friends', 2, 5, 3],
      [1, 'The Schuyler Sisters', 'production', 'Angelica, Eliza, Peggy, Burr', 3, 7, 3],
      [1, 'Farmer Refuted', 'comedy', 'Seabury, Hamilton', 2, 5, 3],
      [1, 'You\'ll Be Back', 'villain', 'King George', 3.5, 5, 4],
      [1, 'Right Hand Man', 'production', 'Washington, Hamilton, Burr', 5, 7, 5],
      [1, 'A Winter\'s Ball', 'charm', 'Burr, Hamilton', 1.5, 6, 2],
      [1, 'Helpless', 'love', 'Eliza, Company', 4, 6, 2],
      [1, 'Satisfied', 'love', 'Angelica, Company', 5.5, 7, 5],
      [1, 'The Story of Tonight (Reprise)', 'reprise', 'Friends, Burr', 1.5, 5, 3],
      [1, 'Wait for It', 'iwant', 'Burr', 3.5, 5, 5],
      [1, 'Stay Alive', 'drive', 'Hamilton, Washington, Co.', 3.5, 6, 5],
      [1, 'Ten Duel Commandments', 'motif', 'Company', 2.5, 7, 6],
      [1, 'Meet Me Inside', 'drive', 'Hamilton, Washington', 2, 6, 6],
      [1, 'That Would Be Enough', 'ballad', 'Eliza, Hamilton', 3, 3, 4],
      [1, 'Guns and Ships', 'production', 'Lafayette, Washington, Co.', 2.5, 9, 5],
      [1, 'History Has Its Eyes on You', 'anthem', 'Washington', 2.5, 4, 6],
      [1, 'Yorktown (The World Turned Upside Down)', 'production', 'Company', 4, 9, 7],
      [1, 'What Comes Next?', 'villain', 'King George', 2, 5, 3],
      [1, 'Dear Theodosia', 'ballad', 'Burr, Hamilton', 3, 3, 3],
      [1, 'Non-Stop', 'finale', 'Company', 6, 8, 6],
      [2, 'What\'d I Miss', 'charm', 'Jefferson, Company', 4, 7, 3],
      [2, 'Cabinet Battle #1', 'production', 'Washington, Jefferson, Hamilton', 3, 8, 6],
      [2, 'Take a Break', 'charm', 'Eliza, Angelica, Philip, Hamilton', 4.5, 5, 4],
      [2, 'Say No to This', 'love', 'Hamilton, Maria, Co.', 3.5, 5, 6],
      [2, 'The Room Where It Happens', 'production', 'Burr, Company', 5, 8, 6],
      [2, 'Schuyler Defeated', 'drive', 'Philip, Eliza, Hamilton, Burr', 1.5, 5, 5],
      [2, 'Cabinet Battle #2', 'production', 'Washington, Jefferson, Hamilton', 2.5, 8, 6],
      [2, 'Washington on Your Side', 'drive', 'Burr, Jefferson, Madison', 3, 7, 7],
      [2, 'One Last Time', 'ballad', 'Washington, Hamilton', 4.5, 4, 5],
      [2, 'I Know Him', 'villain', 'King George', 1.5, 5, 3],
      [2, 'The Adams Administration', 'drive', 'Company', 1, 6, 4],
      [2, 'We Know', 'drive', 'Jefferson, Madison, Burr, Hamilton', 2, 5, 7],
      [2, 'Hurricane', 'soliloquy', 'Hamilton', 3, 4, 7],
      [2, 'The Reynolds Pamphlet', 'production', 'Company', 2.5, 8, 7],
      [2, 'Burn', 'ballad', 'Eliza', 4, 3, 7],
      [2, 'Blow Us All Away', 'drive', 'Philip, Company', 3, 7, 6],
      [2, 'Stay Alive (Reprise)', 'reprise', 'Hamilton, Eliza, Philip', 2.5, 3, 9],
      [2, 'It\'s Quiet Uptown', 'ballad', 'Company, Angelica, Hamiltons', 4, 2, 8],
      [2, 'The Election of 1800', 'production', 'Company', 3.5, 7, 5],
      [2, 'Your Obedient Servant', 'drive', 'Burr, Hamilton', 3, 6, 7],
      [2, 'Best of Wives and Best of Women', 'ballad', 'Eliza, Hamilton', 1.5, 3, 7],
      [2, 'The World Was Wide Enough', 'eleven', 'Burr, Hamilton', 4, 5, 10],
      [2, 'Who Lives, Who Dies, Who Tells Your Story', 'finaleultimo', 'Company', 4, 4, 6],
    ],
  },
};
