// Seed reference shows for the board shell. Each number is a compact tuple:
// [act, title, fn, voicing, estMinutes, energy(1-10), tension(1-10)]
// Energy = tempo/drive, Tension = dramatic stakes. Both interpretive (see SPEC §7).
// Keys / BPM / exact runtimes intentionally omitted ("needs score").

// Default template applied to every new user project.
// 15 blank song cards placed in statistically typical act positions.
// Lane mapping: '1' = Act 1 (pre-break), '2A' = build to intermission,
// '2B' = post-intermission, '3' = late Act 2 through close.
// INTERMISSION marker renders between 2A and 2B.
const DEFAULT_TEMPLATE = [
  // ── Act 1: establish world, voice, first hook ───────────────────
  { act: '1',  type: 'song', title: '', fn: 'opening', voicing: '', min: 4,   energy: 7, tension: 3 },
  { act: '1',  type: 'song', title: '', fn: 'charm',   voicing: '', min: 3,   energy: 6, tension: 3 },
  { act: '1',  type: 'song', title: '', fn: 'iwant',   voicing: '', min: 3.5, energy: 6, tension: 4 },
  // ── Act 2A: complications deepen → threat crystallizes → cliffhanger
  { act: '2A', type: 'song', title: '', fn: 'comedy',  voicing: '', min: 2.5, energy: 6, tension: 3 },
  { act: '2A', type: 'song', title: '', fn: 'love',    voicing: '', min: 3.5, energy: 4, tension: 5 },
  { act: '2A', type: 'song', title: '', fn: 'villain', voicing: '', min: 2.5, energy: 6, tension: 6 },
  { act: '2A', type: 'song', title: '', fn: 'anthem',  voicing: '', min: 3.5, energy: 8, tension: 6 },
  { act: '2A', type: 'song', title: '', fn: 'finale',  voicing: '', min: 4,   energy: 7, tension: 8 },
  // ── Act 2B: regroup → cost mounts → late-act drive ──────────────
  { act: '2B', type: 'song', title: '', fn: 'charm',      voicing: '', min: 3,   energy: 6, tension: 4 },
  { act: '2B', type: 'song', title: '', fn: 'ballad',     voicing: '', min: 3.5, energy: 3, tension: 7 },
  { act: '2B', type: 'song', title: '', fn: 'reprise',    voicing: '', min: 2,   energy: 5, tension: 7 },
  { act: '2B', type: 'song', title: '', fn: 'production', voicing: '', min: 4.5, energy: 9, tension: 7 },
  { act: '2B', type: 'song', title: '', fn: 'anthem',     voicing: '', min: 3.5, energy: 8, tension: 8 },
  // ── Act 3: climax → resolution ──────────────────────────────────
  { act: '3',  type: 'song', title: '', fn: 'eleven',       voicing: '', min: 4.5, energy: 7, tension: 9 },
  { act: '3',  type: 'song', title: '', fn: 'finaleultimo', voicing: '', min: 3,   energy: 6, tension: 5 },
];

const FN = {
  opening:      { fam: 'blue',   label: 'Opening' },
  iwant:        { fam: 'teal',   label: 'I Want' },
  charm:        { fam: 'amber',  label: 'Charm' },
  love:         { fam: 'pink',   label: 'Love' },
  production:   { fam: 'coral',  label: 'Production' },
  soliloquy:    { fam: 'purple', label: 'Soliloquy' },
  ballad:       { fam: 'purple', label: 'Ballad' },
  finale:       { fam: 'blue',   label: 'Act Finale' },
  eleven:       { fam: 'red',    label: "11 O'Clock" },
  reprise:      { fam: 'gray',   label: 'Reprise' },
  finaleultimo: { fam: 'green',  label: 'Finale' },
  villain:      { fam: 'red',    label: 'Villain' },
  comedy:       { fam: 'amber',  label: 'Comedy' },
  anthem:       { fam: 'coral',  label: 'Anthem' },
  diegetic:     { fam: 'gray',   label: 'Diegetic' },
  establishing: { fam: 'gray',   label: 'Establishing' },
  drive:        { fam: 'gray',   label: 'Plot' },
  motif:        { fam: 'green',  label: 'Motif' },
};


const SHOWS = {
  fiddler: {
    title: 'Fiddler on the Roof', year: 1964, form: 'two-act',
    teaches: 'Opening number ("Tradition") establishes world + rules',
    numbers: [
      [1, 'Tradition (Prologue)', 'opening', 'Tevye + Company', 6.5, 7, 3],
      [1, 'Matchmaker, Matchmaker', 'charm', 'Daughters', 3.5, 5, 3],
      [1, 'If I Were a Rich Man', 'iwant', 'Tevye', 4.5, 6, 4],
      [1, 'Sabbath Prayer', 'ballad', 'Tevye, Golde, Co.', 2.5, 3, 4],
      [1, 'To Life (L\'Chaim)', 'production', 'Tevye, Lazar, Men', 4, 9, 5],
      [1, 'Miracle of Miracles', 'charm', 'Motel', 2.5, 6, 4],
      [1, 'The Dream', 'production', 'Tevye, Golde, Ens.', 5, 8, 6],
      [1, 'Sunrise, Sunset', 'finale', 'Company', 4, 5, 7],
      [2, 'Now I Have Everything', 'love', 'Perchik, Hodel', 2.5, 5, 6],
      [2, 'Do You Love Me?', 'love', 'Tevye, Golde', 3, 4, 5],
      [2, 'The Rumor', 'comedy', 'Yente, Villagers', 1.5, 6, 5],
      [2, 'Far From the Home I Love', 'ballad', 'Hodel', 3, 4, 7],
      [2, 'Chavaleh (Little Bird)', 'soliloquy', 'Tevye', 2, 3, 8],
      [2, 'Anatevka', 'finaleultimo', 'Company', 3, 4, 9],
    ],
  },
  gypsy: {
    title: 'Gypsy', year: 1959, form: 'two-act',
    teaches: 'The definitive 11 o\'clock number + driving Act 1 finale',
    numbers: [
      [1, 'Let Me Entertain You (kiddie)', 'diegetic', 'Baby June & Louise', 2, 5, 2],
      [1, 'Some People', 'iwant', 'Rose', 3.5, 6, 4],
      [1, 'Small World', 'love', 'Rose, Herbie', 2.5, 4, 3],
      [1, 'Baby June and Her Newsboys', 'diegetic', 'Baby June + kids', 2, 6, 2],
      [1, 'Mr. Goldstone, I Love You', 'comedy', 'Rose, Company', 2.5, 7, 3],
      [1, 'Little Lamb', 'soliloquy', 'Louise', 2, 2, 4],
      [1, 'You\'ll Never Get Away from Me', 'love', 'Rose, Herbie', 2.5, 4, 3],
      [1, 'Dainty June and Her Farmboys', 'diegetic', 'June + Company', 3, 6, 3],
      [1, 'If Momma Was Married', 'charm', 'June, Louise', 3, 4, 4],
      [1, 'All I Need Is the Girl', 'charm', 'Tulsa', 4, 5, 4],
      [1, 'Everything\'s Coming Up Roses', 'finale', 'Rose', 3.5, 8, 7],
      [2, 'Madame Rose\'s Toreadorables', 'diegetic', 'Rose, Louise, Co.', 2, 6, 4],
      [2, 'Together Wherever We Go', 'charm', 'Rose, Herbie, Louise', 3, 6, 4],
      [2, 'You Gotta Get a Gimmick', 'comedy', 'Tessie, Mazeppa, Electra', 4, 6, 3],
      [2, 'Let Me Entertain You (strip)', 'diegetic', 'Louise / Gypsy', 3.5, 5, 6],
      [2, 'Rose\'s Turn', 'eleven', 'Rose', 4.5, 7, 10],
    ],
  },
  newsies: {
    title: 'Newsies', year: 2012, form: 'two-act',
    teaches: 'Anthem + ensemble production numbers; high-energy contemporary',
    numbers: [
      [1, 'Santa Fe (Prologue)', 'iwant', 'Jack, Crutchie', 2, 4, 3],
      [1, 'Carrying the Banner', 'opening', 'Jack, Davey, Newsies', 4.5, 8, 3],
      [1, 'The Bottom Line', 'villain', 'Pulitzer + cronies', 2.5, 5, 5],
      [1, 'That\'s Rich', 'diegetic', 'Medda Larkin', 2.5, 6, 2],
      [1, 'I Never Planned on You', 'charm', 'Jack, Bowery Beauties', 3, 5, 3],
      [1, 'The World Will Know', 'anthem', 'Jack, Davey, Les, Newsies', 3.5, 8, 6],
      [1, 'Watch What Happens', 'iwant', 'Katherine', 2.5, 5, 4],
      [1, 'Seize the Day', 'production', 'Davey, Jack, Les, Newsies', 4.5, 9, 6],
      [1, 'Santa Fe', 'finale', 'Jack', 4, 7, 7],
      [2, 'King of New York', 'production', 'Davey, Katherine, Les, Newsies', 4.5, 9, 4],
      [2, 'Letter from the Refuge', 'ballad', 'Crutchie', 2.5, 3, 6],
      [2, 'Watch What Happens (Reprise)', 'reprise', 'Jack, Davey, Les, Katherine', 1.5, 5, 6],
      [2, 'Brooklyn\'s Here', 'production', 'Spot Conlon, Newsies', 2.5, 8, 6],
      [2, 'Something to Believe In', 'love', 'Jack, Katherine', 3.5, 4, 5],
      [2, 'Once and for All', 'anthem', 'Jack, Katherine, Davey, Newsies', 3.5, 8, 8],
      [2, 'Finale (Santa Fe reprise)', 'finaleultimo', 'Company', 2, 7, 3],
    ],
    // Full scene-by-scene story: 16 songs + ~38 book-scene beats, hand-placed lanes.
    // Break into 2 = "The World Will Know"; intermission after "Santa Fe";
    // Break into 3 (Act 3 start) = "Brooklyn's Here".
    cards: [
      // ACT 1
      { lane: '1', type: 'scene', title: 'Brooklyn Rooftop' },
      { lane: '1', type: 'song', title: 'Santa Fe (Prologue)', fn: 'iwant', voicing: 'Jack, Crutchie', min: 2, energy: 4, tension: 3 },
      { lane: '1', type: 'beat', title: 'Rooftop at dawn', note: 'Jack sketches the Santa Fe dream; Crutchie\'s bad leg, his loyalty', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Snyder the Spider', note: 'The Refuge warden hunts runaways; Jack, an escapee, keeps his head down', min: 1 },
      { lane: '1', type: 'scene', title: 'Streets of Manhattan' },
      { lane: '1', type: 'song', title: 'Carrying the Banner', fn: 'opening', voicing: 'Jack, Newsies', min: 4.5, energy: 8, tension: 3 },
      { lane: '1', type: 'beat', title: 'The distribution gates', note: 'Wiesel and the Delanceys hawk the papes; Davey and Les arrive needing to earn', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Jack takes the boys in', note: 'He teaches Davey & Les to sell — and sizes up his new partners', min: 1.5 },
      { lane: '1', type: 'scene', title: "Pulitzer's Office" },
      { lane: '1', type: 'song', title: 'The Bottom Line', fn: 'villain', voicing: 'Pulitzer + cronies', min: 2.5, energy: 5, tension: 5 },
      { lane: '1', type: 'beat', title: 'The price hike hits', note: 'The World ups the price 10¢ per hundred; Davey names it — they\'re being robbed', min: 1.5 },
      { lane: '1', type: 'beat', title: 'Scuffle at the gates', note: 'The Delanceys shove Les; Jack steps in; the boys duck into Medda\'s', min: 1.5 },
      { lane: '1', type: 'scene', title: "Medda's Theater" },
      { lane: '1', type: 'song', title: "That's Rich", fn: 'diegetic', voicing: 'Medda Larkin', min: 2.5, energy: 6, tension: 2 },
      { lane: '1', type: 'beat', title: 'Jack meets Katherine', note: 'Sparks in the wings with the young reporter; he sketches her', min: 1.5 },
      { lane: '1', type: 'song', title: 'I Never Planned on You', fn: 'charm', voicing: 'Jack', min: 3, energy: 5, tension: 3 },
      { lane: '1', type: 'beat', title: 'The idea: a strike', note: 'Jack pitches it; Davey the reluctant brains signs on', min: 1.5 },
      // ACT 2A
      { lane: '2A', type: 'scene', title: 'Newsies Square' },
      { lane: '2A', type: 'song', title: 'The World Will Know', fn: 'anthem', voicing: 'Jack, Davey, Les, Newsies', min: 3.5, energy: 8, tension: 6 },
      { lane: '2A', type: 'beat', title: 'Forming the union', note: 'The newsies organize and name Jack & Davey their leaders', min: 1.5 },
      { lane: '2A', type: 'scene', title: 'The Sun — City Room' },
      { lane: '2A', type: 'beat', title: 'Katherine smells a story', note: 'She pitches the strike to her skeptical editor', min: 1.5 },
      { lane: '2A', type: 'song', title: 'Watch What Happens', fn: 'iwant', voicing: 'Katherine', min: 2.5, energy: 5, tension: 4 },
      { lane: '2A', type: 'scene', title: 'Distribution Gates — Strike Day' },
      { lane: '2A', type: 'beat', title: 'Strike morning', note: 'The newsies mass at the distribution window and refuse to sell', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'The scabs arrive', note: 'Wiesel brings in replacement boys to sell the papes', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'Winning over the scabs', note: 'The newsies argue, shame, and welcome the scabs into the cause', min: 2 },
      { lane: '2A', type: 'song', title: 'Seize the Day', fn: 'production', voicing: 'Davey, Jack, Les, Newsies', min: 4.5, energy: 9, tension: 6 },
      { lane: '2A', type: 'beat', title: 'The crackdown', note: 'The Delanceys and police charge; the rally erupts into a riot', min: 2 },
      { lane: '2A', type: 'beat', title: 'Crutchie is taken', note: 'Snyder\'s men beat Crutchie and drag him to the Refuge', min: 1.5 },
      { lane: '2A', type: 'beat', title: 'Jack runs', note: 'Alone on the rooftop, blaming himself, watching the city', min: 1 },
      { lane: '2A', type: 'song', title: 'Santa Fe', fn: 'finale', voicing: 'Jack', min: 4, energy: 7, tension: 7 },
      // ACT 2B
      { lane: '2B', type: 'scene', title: 'Newsies Lodging House' },
      { lane: '2B', type: 'beat', title: 'Front page', note: 'The strike is the talk of the city; the newsies are famous', min: 1.5 },
      { lane: '2B', type: 'song', title: 'King of New York', fn: 'production', voicing: 'Davey, Katherine, Les, Newsies', min: 4.5, energy: 9, tension: 4 },
      { lane: '2B', type: 'scene', title: "Medda's — Backstage" },
      { lane: '2B', type: 'beat', title: 'Jack in hiding', note: 'Painting backdrops at Medda\'s, done with the fight', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'Katherine pushes back', note: 'She refuses to let him quit', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'At the Refuge', note: 'Crutchie, hurting but unbroken, dreams of Jack and Santa Fe', min: 1 },
      { lane: '2B', type: 'song', title: 'Letter from the Refuge', fn: 'ballad', voicing: 'Crutchie', min: 2.5, energy: 3, tension: 6 },
      { lane: '2B', type: 'beat', title: "Katherine's secret", note: 'She\'s Pulitzer\'s daughter; trust wobbles', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'The plan', note: 'Rally every working kid in New York; beat Pulitzer with his own press', min: 1.5 },
      { lane: '2B', type: 'song', title: 'Watch What Happens (Reprise)', fn: 'reprise', voicing: 'Jack, Davey, Les, Katherine', min: 1.5, energy: 5, tension: 6 },
      { lane: '2B', type: 'scene', title: "Pulitzer's Office" },
      { lane: '2B', type: 'beat', title: 'Summoned by Pulitzer', note: 'Jack is hauled before Pulitzer; Snyder waits in the office', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'The bribe', note: 'Money and freedom from the Refuge if Jack calls off the strike', min: 2 },
      { lane: '2B', type: 'beat', title: 'Jack folds', note: 'Publicly he tells the boys to give up; the cause looks dead — all is lost', min: 1.5 },
      { lane: '2B', type: 'beat', title: 'Betrayed', note: 'Davey and the newsies turn on Jack; Katherine won\'t quit', min: 1.5 },
      // ACT 3
      { lane: '3', type: 'scene', title: 'The Streets — Midtown' },
      { lane: '3', type: 'song', title: "Brooklyn's Here", fn: 'production', voicing: 'Spot Conlon, Newsies', min: 2.5, energy: 8, tension: 6 },
      { lane: '3', type: 'beat', title: 'Jack recommits', note: 'Katherine shows him the way; the cellar printing plan', min: 1.5 },
      { lane: '3', type: 'song', title: 'Something to Believe In', fn: 'love', voicing: 'Jack, Katherine', min: 3.5, energy: 4, tension: 5 },
      { lane: '3', type: 'scene', title: "The World's Press Room" },
      { lane: '3', type: 'beat', title: 'Printing the Banner', note: 'Overnight, in the World\'s own cellar, they print their paper', min: 2 },
      { lane: '3', type: 'beat', title: 'The city rises', note: 'Every working kid in New York reads the call to strike', min: 1.5 },
      { lane: '3', type: 'song', title: 'Once and for All', fn: 'anthem', voicing: 'Jack, Katherine, Davey, Newsies', min: 3.5, energy: 8, tension: 8 },
      { lane: '3', type: 'beat', title: 'Roosevelt arrives', note: 'Jack\'s Refuge drawings expose Snyder; the Governor intervenes', min: 2 },
      { lane: '3', type: 'beat', title: 'Pulitzer concedes', note: 'Snyder arrested, Crutchie freed, the price rolled back', min: 1.5 },
      { lane: '3', type: 'beat', title: 'Jack stays', note: 'He chooses New York, Katherine, and the newsies over Santa Fe', min: 1.5 },
      { lane: '3', type: 'song', title: 'Finale (Santa Fe reprise)', fn: 'finaleultimo', voicing: 'Company', min: 2, energy: 7, tension: 3 },
    ],
  },
  hamilton: {
    title: 'Hamilton', year: 2015, form: 'two-act',
    teaches: 'Through-composition + motif density; delayed payoff',
    numbers: [
      [1, 'Alexander Hamilton', 'opening', 'Company', 4, 6, 3],
      [1, 'Aaron Burr, Sir', 'establishing', 'Burr, Hamilton +3', 2.5, 5, 3],
      [1, 'My Shot', 'iwant', 'Hamilton +3', 5.5, 8, 4],
      [1, 'The Story of Tonight', 'anthem', 'Hamilton + friends', 2, 5, 3],
      [1, 'The Schuyler Sisters', 'production', 'Angelica, Eliza, Peggy, Burr', 3, 7, 3],
      [1, 'Farmer Refuted', 'comedy', 'Seabury, Hamilton', 2, 5, 3],
      [1, 'You\'ll Be Back', 'villain', 'King George', 3.5, 5, 4],
      [1, 'Right Hand Man', 'production', 'Washington, Hamilton, Burr', 5, 7, 5],
      [1, 'A Winter\'s Ball', 'charm', 'Burr, Hamilton', 1.5, 6, 2],
      [1, 'Helpless', 'love', 'Eliza, Company', 4, 6, 2],
      [1, 'Satisfied', 'love', 'Angelica, Company', 5.5, 7, 5],
      [1, 'The Story of Tonight (Reprise)', 'reprise', 'Friends, Burr', 1.5, 5, 3],
      [1, 'Wait for It', 'iwant', 'Burr', 3.5, 5, 5],
      [1, 'Stay Alive', 'drive', 'Hamilton, Washington, Co.', 3.5, 6, 5],
      [1, 'Ten Duel Commandments', 'motif', 'Company', 2.5, 7, 6],
      [1, 'Meet Me Inside', 'drive', 'Hamilton, Washington', 2, 6, 6],
      [1, 'That Would Be Enough', 'ballad', 'Eliza, Hamilton', 3, 3, 4],
      [1, 'Guns and Ships', 'production', 'Lafayette, Washington, Co.', 2.5, 9, 5],
      [1, 'History Has Its Eyes on You', 'anthem', 'Washington', 2.5, 4, 6],
      [1, 'Yorktown (The World Turned Upside Down)', 'production', 'Company', 4, 9, 7],
      [1, 'What Comes Next?', 'villain', 'King George', 2, 5, 3],
      [1, 'Dear Theodosia', 'ballad', 'Burr, Hamilton', 3, 3, 3],
      [1, 'Non-Stop', 'finale', 'Company', 6, 8, 6],
      [2, 'What\'d I Miss', 'charm', 'Jefferson, Company', 4, 7, 3],
      [2, 'Cabinet Battle #1', 'production', 'Washington, Jefferson, Hamilton', 3, 8, 6],
      [2, 'Take a Break', 'charm', 'Eliza, Angelica, Philip, Hamilton', 4.5, 5, 4],
      [2, 'Say No to This', 'love', 'Hamilton, Maria, Co.', 3.5, 5, 6],
      [2, 'The Room Where It Happens', 'production', 'Burr, Company', 5, 8, 6],
      [2, 'Schuyler Defeated', 'drive', 'Philip, Eliza, Hamilton, Burr', 1.5, 5, 5],
      [2, 'Cabinet Battle #2', 'production', 'Washington, Jefferson, Hamilton', 2.5, 8, 6],
      [2, 'Washington on Your Side', 'drive', 'Burr, Jefferson, Madison', 3, 7, 7],
      [2, 'One Last Time', 'ballad', 'Washington, Hamilton', 4.5, 4, 5],
      [2, 'I Know Him', 'villain', 'King George', 1.5, 5, 3],
      [2, 'The Adams Administration', 'drive', 'Company', 1, 6, 4],
      [2, 'We Know', 'drive', 'Jefferson, Madison, Burr, Hamilton', 2, 5, 7],
      [2, 'Hurricane', 'soliloquy', 'Hamilton', 3, 4, 7],
      [2, 'The Reynolds Pamphlet', 'production', 'Company', 2.5, 8, 7],
      [2, 'Burn', 'ballad', 'Eliza', 4, 3, 7],
      [2, 'Blow Us All Away', 'drive', 'Philip, Company', 3, 7, 6],
      [2, 'Stay Alive (Reprise)', 'reprise', 'Hamilton, Eliza, Philip', 2.5, 3, 9],
      [2, 'It\'s Quiet Uptown', 'ballad', 'Company, Angelica, Hamiltons', 4, 2, 8],
      [2, 'The Election of 1800', 'production', 'Company', 3.5, 7, 5],
      [2, 'Your Obedient Servant', 'drive', 'Burr, Hamilton', 3, 6, 7],
      [2, 'Best of Wives and Best of Women', 'ballad', 'Eliza, Hamilton', 1.5, 3, 7],
      [2, 'The World Was Wide Enough', 'eleven', 'Burr, Hamilton', 4, 5, 10],
      [2, 'Who Lives, Who Dies, Who Tells Your Story', 'finaleultimo', 'Company', 4, 4, 6],
    ],
  },
};
